  name: Bromance
  main: com.yjcreate.BromanceApplication
  version: 1.0.0
  description: A light weight plugin for the players who want to play with their bromance through connecting Server.
  api-version: 1.20.1
  author: Yjiang
  prefix: Bromance-Log
  commands:
    fly:
      description: Use that you can fly to sky
      permission: bromance.fly
      permission-message: You do not have permission!
      usage: /<command> [player]
  permissions:
    bromance.fly:
      description: Allows player fly
      default: op